title: Lattyware
author: Gareth Latty
email: gareth@lattyware.co.uk
language: en-gb
url: "https://www.lattyware.co.uk"
baseurl: ""

markdown: kramdown

paginate: 5
paginate_path: "/blog/page:num/"

permalink: pretty

gems: [jekyll-paginate]
