title: Lattyware
author: Gareth Latty
email: gareth@lattyware.co.uk
language: en-gb
url: "https://www.lattyware.co.uk"
baseurl: ""

markdown: kramdown

sass:
  style: compressed

paginate: 5
paginate_path: "/blog/page:num/"

permalink: pretty

image: /images/logo.png

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-auto-image

exclude:
  - Gemfile
  - Gemfile.lock
